Loading message for survey creation
ELEVATE-Project/template-validation-portal pull request #47
Opened 2024-10-03 10:03 UTC by anudeep1706

2024-10-03 13:30 UTC, 5Amogh requested changes

2024-10-03 13:30 UTC, 5Amogh commented on src/app/modules/template/template-selection/template-selection.component.ts
> +    this.loadingMessage = 'Survey creation is in progress. Please wait...'; // Set initial loading message
loading message is specific and so does the function name and all, shouldn't those be generalized?

2024-10-03 13:30 UTC, 5Amogh commented on src/app/modules/template/template-selection/template-selection.component.ts
> +                this.loadingMessage = 'Survey validation failed. Please check the errors.'; // Update loading message to validation failure
same feedback as above

2024-10-04 04:20 UTC, anudeep1706 commented on src/app/modules/template/template-selection/template-selection.component.ts
> +    this.loadingMessage = 'Survey creation is in progress. Please wait...'; // Set initial loading message
Currently this code we are customising to KBs requirements. There is another code we are maintaining for generalizing all the solutions.

2024-10-04 06:13 UTC, 5Amogh approved these changes

2024-10-04 06:16 UTC, merged